# Include all library() calls to the packages 
# that are used in the project
libaray(devtools)
libaray(knitr)
library(rmarkdown)
library(stats)
library(base)
library(utils)
library(grDevices)
library(graphics)
library(testthat)
library(plyr)
library(pls)
library(glmnet)
library(pls)
libaray(FactoMinoR)
libaray(ggplot2)

sink('session-info.txt')
cat("Session Information\n\n")
print(sessionInfo())
devtools::session_info()
sessionInfo()
sink()